config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :appointments
  devise_for :users

  root 'appointments#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  has_rich_text :Description
  belongs_to :user
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  has_rich_text :Text
  belongs_to :user
  belongs_to :appointment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :appointments
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:name, :description, :start_time, :end_time, :day, :user_id, :appointment_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:text, :user_id, :scheduled, :send_time, :status, :appointment_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>">
  <p>
    <strong>Name:</strong>
    <%= appointment.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= appointment.description %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= appointment.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= appointment.end_time %>
  </p>

  <p>
    <strong>Day:</strong>
    <%= appointment.day %>
  </p>

  <p>
    <strong>User:</strong>
    <%= appointment.user_id %>
  </p>

</div>

app/views/appointments/_form.html.erb
<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
    <div class="col-md-6">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, class:"form-control" %>
    </div>
    <div class="col-md-6">
      <%= form.label :day, style: "display: block" %>
      <%= form.date_field :day, class:"form-control" %>
    </div>
</div> 
<div class="row">
    <div claass="col-md-6">
      <%= form.label :start_time, style: "display: block" %>
      <%= form.datetime_field :start_time, class:"form-control" %>
    </div>

    <div class="col-md-6">
      <%= form.label :end_time, style: "display: block" %>
      <%= form.datetime_field :end_time, class:"form-control" %>
    </div>
</div> 

<div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description, class:"form-control" %>
</div>
  <br>

<%= turbo_frame_tag 'new_message' do %>
<div class="row"></div>
  <h4>Notifications</h4>
  <div class="col d-flex flex-row-reverse">
    <%= link_to 'Add New Notification', new_message_path, class: "btn btn-primary" %>
  </div>
</div>  
<% end %>
<br><br>
<div class="col d-flex flex-row-reverse">
    <%= form.submit 'Save', class:"btn btn-secondary" %>
 </div>
  
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render "form", appointment: @appointment %>

<br>

<div>
  <%= link_to "Show this appointment", @appointment %> |
  <%= link_to "Back to appointments", appointments_path %>
</div>

app/views/appointments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Appointments</h1>

<div id="appointments">
  <% @appointments.each do |appointment| %>
    <%= render appointment %>
    <p>
      <%= link_to "Show this appointment", appointment %>
    </p>
  <% end %>
</div>

<%= link_to "New appointment", new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render "form", appointment: @appointment %>

<br>

<div>
  <%= link_to "Back to appointments", appointments_path %>
</div>

app/views/appointments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @appointment %>

<div>
  <%= link_to "Edit this appointment", edit_appointment_path(@appointment) %> |
  <%= link_to "Back to appointments", appointments_path %>

  <%= button_to "Destroy this appointment", @appointment, method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appointments App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="modal" tabindex="-1">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="row">
                <div class="col-md-6">
                  <%= form.label :send_time, style: "display: block" %>
                  <%= form.datetime_field :send_time, class:"form-control" %>
                </div>
                <div class="col-md-6">
                  <%= form.label :text, style: "display: block" %>
                  <%= form.text_area :text, class:"form-control" %>
                </div>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
  </div>

<div>
   <%= form.submit class:"btn btn-dark" %>
</div>

    
      
      
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Text:</strong>
    <%= message.text %>
  </p>

  <p>
    <strong>User:</strong>
    <%= message.user_id %>
  </p>

  <p>
    <strong>Scheduled:</strong>
    <%= message.scheduled %>
  </p>

  <p>
    <strong>Send time:</strong>
    <%= message.send_time %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= message.status %>
  </p>

  <p>
    <strong>Appointment:</strong>
    <%= message.appointment_id %>
  </p>

</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= turbo_frame_tag @message do %>
  <h4>Notifications</h4>
  <div class="col d-flex flex-row-reverse">
    <%= link_to 'Add New Notification', new_message_path, class: "btn btn-primary" %>
  </div>
  <%= render "form", message: @message %>
<% end %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>